---
- name: Deploy RIC on OCP Playbook
  hosts: localhost
  tasks:
    - name: Load sctp config and hostpath config, then install helm
      shell: |
        curl -o load-sctp-module.yaml https://raw.githubusercontent.com/xphyr/ocp-ric/master/load-sctp-module.yaml
        oc create -f load-sctp-module.yaml
        curl -o seconfig_hostpath.yaml https://raw.githubusercontent.com/xphyr/ocp-ric/master/seconfig_hostpath.yaml
        oc create -f seconfig_hostpath.yaml
        curl -o helm-v2.16.10-linux-amd64.tar.gz https://get.helm.sh/helm-v2.16.10-linux-amd64.tar.gz
        tar -zxvf helm-v2.16.10-linux-amd64.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm

    - name: Check if directory exists
      stat:
        path: ocp-ric
      register: dir_to_delete

    - name: Delete existing directory
      shell: |
        rm -Rf ocp-ric
      when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir

    - name: Clone the git repo
      command: git clone https://github.com/xphyr/ocp-ric.git

    - name: update repo
      shell: |
        git submodule update --init --recursive --remote
      args:
        chdir: ocp-ric/

    - name: create tiller project and initialize helm
      shell: |
        oc new-project tiller
        oc project tiller
        helm init --client-only
      environment:
        TILLER_NAMESPACE: tiller
      args:
        chdir: ocp-ric/

    - name: download tiller template
      shell: |
        curl -o tiller-template.yaml https://raw.githubusercontent.com/xphyr/ocp-ric/master/tiller-template.yaml
      args:
        chdir: ocp-ric/

    - name: create tiller process
      shell: |
        oc process -f tiller-template.yaml -p TILLER_NAMESPACE="${TILLER_NAMESPACE}" -p HELM_VERSION=v2.16.10 | oc create -f -
      environment:
        TILLER_NAMESPACE: tiller
      ignore_errors: True
      args:
        chdir: ocp-ric/

    - name: wait for helm to come up
      shell: helm version
      register: helm_version
      until: helm_version.stdout.find("Client") != -1 and helm_version.stdout.find("Server") != -1
      delay: 5
      retries: 10
      environment:
        TILLER_NAMESPACE: tiller

    - name: give admin access to service account, patch the ric files and deploy
      shell: |
        oc project ricplt
        oc adm policy add-cluster-role-to-user cluster-admin "system:serviceaccount:${TILLER_NAMESPACE}:tiller"
        patches/apply-ric-patch.sh
        dep/bin/deploy-ric-platform dep/RECIPE_EXAMPLE/PLATFORM/example_recipe.yaml
      environment:
        TILLER_NAMESPACE: tiller
      args:
        chdir: ocp-ric/
