apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-09-09T16:01:20Z"
  generation: 1
  labels:
    app: ricplt-e2term-alpha
    chart: e2term-3.0.0
    heritage: Tiller
    release: r4-e2term
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
            f:release: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:release: {}
          f:spec:
            f:containers:
              k:{"name":"container-ricplt-e2term"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"MY_POD_IP_SERVICE_HOST"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef:
                        .: {}
                        f:apiVersion: {}
                        f:fieldPath: {}
                f:envFrom: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":4561,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":8088,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":36422,"protocol":"SCTP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":38000,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:exec:
                    .: {}
                    f:command: {}
                  f:failureThreshold: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:privileged: {}
                f:stdin: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:tty: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/data/outgoing/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/opt/e2/router.txt"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:subPath: {}
                  k:{"mountPath":"/tmp/rmr_verbose"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:subPath: {}
            f:dnsPolicy: {}
            f:hostname: {}
            f:imagePullSecrets:
              .: {}
              k:{"name":"secret-nexus3-o-ran-sc-org-10002-o-ran-sc"}:
                .: {}
                f:name: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"local-router-file"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:name: {}
                f:name: {}
              k:{"name":"vol-shared"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
    manager: Go-http-client
    operation: Update
    time: "2020-09-09T16:01:20Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-09T16:01:43Z"
  name: deployment-ricplt-e2term-alpha
  namespace: ricplt
  resourceVersion: "78728613"
  selfLink: /apis/apps/v1/namespaces/ricplt/deployments/deployment-ricplt-e2term-alpha
  uid: f69e31ef-12cd-48e8-bf54-fdb975cfd68c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ricplt-e2term-alpha
      release: r4-e2term
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: e2ric
      creationTimestamp: null
      labels:
        app: ricplt-e2term-alpha
        release: r4-e2term
    spec:
      containers:
      - env:
        - name: MY_POD_IP_SERVICE_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: configmap-ricplt-e2term-env-alpha
        image: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-e2:5.0.8
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/e2/rmr_probe -h 0.0.0.0:38000
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: container-ricplt-e2term
        ports:
        - containerPort: 4561
          name: rmrroute-alpha
          protocol: TCP
        - containerPort: 38000
          name: rmrdata-alpha
          protocol: TCP
        - containerPort: 36422
          name: sctp-alpha
          protocol: SCTP
        - containerPort: 8088
          name: prmts-alpha
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/e2/rmr_probe -h 0.0.0.0:38000
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/e2/router.txt
          name: local-router-file
          subPath: router.txt
        - mountPath: /tmp/rmr_verbose
          name: local-router-file
          subPath: rmr_verbose
        - mountPath: /data/outgoing/
          name: vol-shared
      dnsPolicy: ClusterFirstWithHostNet
      hostname: e2term-alpha
      imagePullSecrets:
      - name: secret-nexus3-o-ran-sc-org-10002-o-ran-sc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: configmap-ricplt-e2term-router-configmap
        name: local-router-file
      - name: vol-shared
        persistentVolumeClaim:
          claimName: pvc-ricplt-e2term-alpha
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-09T16:01:43Z"
    lastUpdateTime: "2020-09-09T16:01:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-09T16:01:20Z"
    lastUpdateTime: "2020-09-09T16:01:43Z"
    message: ReplicaSet "deployment-ricplt-e2term-alpha-5f4b547cbb" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
